name: Restrict Access to Web Folder

# Especifica cuándo debe ejecutarse el workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  restrict_access:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Verificar que el usuario esté en la lista de autorizados
      - name: Check User Authorization
        id: auth_check
        run: |
          # Lista de usuarios autorizados
          AUTHORIZED_USERS=("X4VICO" "Sote19" "Zz00mer") # Reemplaza con los nombres de usuario autorizados
          
          # Verificar si el usuario que activó el workflow está en la lista
          if [[ ! " ${AUTHORIZED_USERS[@]} " =~ " ${{ github.actor }} " ]]; then
            echo "Unauthorized access attempt by ${{ github.actor }} to the 'web' folder."
            exit 1
          fi

      # Paso 2: Checkout del repositorio si la verificación fue exitosa
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Paso 3: Acceso a la carpeta web para operaciones restringidas
      - name: Access Web Folder
        run: |
          echo "Access granted to 'web' folder for ${{ github.actor }}"
          # Aquí puedes ejecutar cualquier comando relacionado con los archivos en la carpeta 'web'
          ls web
